import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = process.cwd();
const catalogPath = path.join(root, 'src', 'data', 'catalog-data.ts');
const outputPath = path.join(root, 'migrations', '0002_seed_catalog.sql');

function loadCatalogData() {
  const source = fs.readFileSync(catalogPath, 'utf8');
  const executable = source
    .replace(/^\/\/.*$/gm, '')
    .replace('export const generatedSeries =', 'const generatedSeries =')
    .replace('export const generatedBooks =', 'const generatedBooks =')
    .replace(/ as const;/g, ';')
    .concat('\nmodule.exports = { generatedSeries, generatedBooks };');

  const sandbox = {
    module: { exports: {} },
    exports: {},
  };

  vm.runInNewContext(executable, sandbox, {
    filename: 'catalog-data.ts',
  });

  return sandbox.module.exports;
}

function sqlString(value) {
  if (value === null || value === undefined || value === '') {
    return 'NULL';
  }

  return `'${String(value).replaceAll("'", "''")}'`;
}

function sqlBoolean(value) {
  return value ? '1' : '0';
}

function firstRetailerLink(book, predicate) {
  return book.purchase?.retailerLinks?.find(predicate)?.purchaseUrl ?? null;
}

function firstDirectLink(book) {
  return book.purchase?.directSaleFormats?.find((item) => item.purchaseUrl)?.purchaseUrl ?? null;
}

const { generatedSeries, generatedBooks } = loadCatalogData();

const lines = [
  '-- Generated by scripts/generate_d1_seed.mjs',
  'PRAGMA foreign_keys = ON;',
  '',
  'DELETE FROM site_settings;',
  'DELETE FROM books;',
  "DELETE FROM sqlite_sequence WHERE name = 'books';",
  'DELETE FROM series;',
  "DELETE FROM sqlite_sequence WHERE name = 'series';",
  '',
];

generatedSeries.forEach((series, index) => {
  lines.push(
    `INSERT INTO series (` +
      'slug, name, lane, tagline, description, entry_point, ' +
      'gradient_start, gradient_mid, gradient_end, text_color, visible, sort_priority' +
    `) VALUES (` +
      [
        sqlString(series.slug),
        sqlString(series.name),
        sqlString(series.lane),
        sqlString(series.tagline),
        sqlString(series.description),
        sqlString(series.entryPoint),
        sqlString(series.gradient?.[0] ?? '#241920'),
        sqlString(series.gradient?.[1] ?? '#6f425e'),
        sqlString(series.gradient?.[2] ?? '#c48273'),
        sqlString(series.textColor ?? '#fff5f0'),
        '1',
        String((index + 1) * 10),
      ].join(', ') +
    ');',
  );
});

lines.push('');

generatedBooks.forEach((book, index) => {
  const amazonLink = firstRetailerLink(
    book,
    (item) => item.retailer === 'Amazon' || item.label?.toLowerCase().includes('amazon'),
  );
  const retailerLink = firstRetailerLink(
    book,
    (item) => !(item.retailer === 'Amazon' || item.label?.toLowerCase().includes('amazon')),
  );
  const directLink = firstDirectLink(book);
  const coverImageUrl = `/covers/${book.slug}.jpg`;
  const seriesReference = book.seriesSlug
    ? `(SELECT id FROM series WHERE slug = ${sqlString(book.seriesSlug)})`
    : 'NULL';
  const seriesLabelOverride = !book.seriesSlug && book.seriesLabel
    ? sqlString(book.seriesLabel)
    : 'NULL';

  lines.push(
    `INSERT INTO books (` +
      'slug, title, series_id, series_label_override, series_order, publish_year, release_date, ' +
      'cover_image_url, short_blurb, description, availability_status, availability_label, ' +
      'amazon_link, retailer_link, stripe_payment_link, display_price, signed_copy, direct_from_author, visible, sort_priority, cover_palette, catalog_status, featured, genres_json, formats_json' +
    `) VALUES (` +
      [
        sqlString(book.slug),
        sqlString(book.title),
        seriesReference,
        seriesLabelOverride,
        String(Number(book.seriesOrder ?? 0)),
        book.releaseDate ? String(new Date(book.releaseDate).getUTCFullYear()) : 'NULL',
        sqlString(book.releaseDate),
        sqlString(coverImageUrl),
        sqlString(book.shortHook),
        sqlString(book.description),
        sqlString(book.purchase?.availabilityStatus ?? 'in_stock'),
        sqlString(book.purchase?.availabilityLabel ?? null),
        sqlString(amazonLink),
        sqlString(retailerLink),
        sqlString(directLink),
        'NULL',
        sqlBoolean(Boolean(book.purchase?.signedCopy)),
        sqlBoolean(Boolean(book.purchase?.directFromAuthor)),
        '1',
        String((index + 1) * 10),
        sqlString(book.coverPalette ?? 'plum'),
        sqlString(book.catalogStatus ?? ''),
        sqlBoolean(Boolean(book.featured)),
        sqlString(JSON.stringify(book.genres ?? [])),
        sqlString(JSON.stringify(book.formats ?? [])),
      ].join(', ') +
    ');',
  );
});

lines.push('');
lines.push(
  `INSERT INTO site_settings (key, value) VALUES (${sqlString('direct_sales_signed_copy_note')}, ${sqlString('Signed copy updates will be shared on the site and in the newsletter.')});`,
);
lines.push(
  `INSERT INTO site_settings (key, value) VALUES (${sqlString('direct_sales_shipping_note')}, '');`,
);
lines.push(
  `INSERT INTO site_settings (key, value) VALUES (${sqlString('direct_sales_fulfillment_note')}, '');`,
);
lines.push(
  `INSERT INTO site_settings (key, value) VALUES (${sqlString('direct_sales_where_to_buy_note')}, '');`,
);
lines.push('');

fs.writeFileSync(outputPath, `${lines.join('\n')}\n`, 'utf8');
console.log(outputPath);
